[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"
